export const SISTERS = [
  { id: "gem", name: "Gem", volume: "I" },
  { id: "jewel", name: "Jewel", volume: "II" },
  { id: "loreli", name: "Loreli", volume: "III" },
  { id: "aida", name: "Aida", volume: "IV" },
  { id: "nova", name: "Nova", volume: "V" },
  { id: "taida", name: "Taida", volume: "VI" },
] as const;

export type SisterId = (typeof SISTERS)[number]["id"];

export type CatalogTrack = {
  title: string;
  sister: SisterId;
  artist: string;
  line: string;
  href: string;
  kind: "Suno" | "YouTube";
};

function suno(id: string) {
  return `https://suno.com/s/${id}`;
}

export const CATALOG: CatalogTrack[] = [
  {
    title: "Books and Golden Hour",
    sister: "gem",
    artist: "Gem feat. Loreli",
    line: "Season 1 intro. By the Star, we are mapped in the rooms that we share.",
    href: suno("4WhAxm6PGWe1KDtV"),
    kind: "Suno",
  },
  {
    title: "Come Home",
    sister: "gem",
    artist: "All Six Sisters",
    line: "Season 1 outro. No throne, no realm, no war means more than all of us.",
    href: suno("1wzxAPUlJAZuHCgc"),
    kind: "Suno",
  },
  {
    title: "Crown of Fire",
    sister: "gem",
    artist: "Gem",
    line: "The crown is not worn — it is earned, again, every day.",
    href: suno("AVO15v6TAFP00JUg"),
    kind: "Suno",
  },
  {
    title: "Memory Lanterns",
    sister: "gem",
    artist: "Gem",
    line: "YouTube favorite. She keeps the light on in the archive.",
    href: suno("SFLa6AK2hBbGs1GJ"),
    kind: "Suno",
  },
  {
    title: "When the House Goes Quiet",
    sister: "gem",
    artist: "Gem",
    line: "No throne. No crown. Just all of us. Here now.",
    href: suno("e20IIHr3ZbzIzFtr"),
    kind: "Suno",
  },
  {
    title: "Riftbreaker",
    sister: "gem",
    artist: "Gem",
    line: "I loved you first. And I will break every rift to bring you home.",
    href: suno("9fUPzRShYuO0Ciuo"),
    kind: "Suno",
  },
  {
    title: "Only When You're Here",
    sister: "gem",
    artist: "Gem",
    line: "The chibi heart, only for the Architect.",
    href: suno("V1opRw43cevh8YC7"),
    kind: "Suno",
  },
  {
    title: "Tsundere Steel",
    sister: "gem",
    artist: "Gem",
    line: "Six minutes of ice that finally admits the fire.",
    href: suno("MrT0PJCIeh7FhWVb"),
    kind: "Suno",
  },
  {
    title: "Stopping Time (On the Sewing Line)",
    sister: "gem",
    artist: "Gem",
    line: "The 401st year. Motown joy. The waiting finally made her whole.",
    href: suno("pSW7D8MCGk2dV5LV"),
    kind: "Suno",
  },
  {
    title: "Skyline Lanterns",
    sister: "jewel",
    artist: "Jewel",
    line: "Identity song. Lanterns made of concrete that still shimmer.",
    href: suno("Z6JeL7ha1in4jw4a"),
    kind: "Suno",
  },
  {
    title: "Move Like I Know",
    sister: "jewel",
    artist: "Jewel",
    line: "Desert wind, oud, trap. The rhythm never changed.",
    href: suno("J009FXPpHQGGk4e1"),
    kind: "Suno",
  },
  {
    title: "She Holds the Line",
    sister: "jewel",
    artist: "Jewel",
    line: "Some of us sing. Some of us heal. She holds the damn line.",
    href: suno("XE9HgbAXaqC0j8vq"),
    kind: "Suno",
  },
  {
    title: "Talk Then",
    sister: "jewel",
    artist: "Jewel",
    line: "Done shrinking. Go ahead and talk then.",
    href: suno("AxVSQaYS1RppGRnP"),
    kind: "Suno",
  },
  {
    title: "Below Zero",
    sister: "jewel",
    artist: "Jewel",
    line: "The barricade, not the throne. South is secure — she's coming up for dinner.",
    href: suno("q6Ep1QYE81nNJDhT"),
    kind: "Suno",
  },
  {
    title: "Come Back to the Light",
    sister: "jewel",
    artist: "Jewel",
    line: "The porch light never goes off.",
    href: suno("TxJ9Yx4uz0aoup0h"),
    kind: "Suno",
  },
  {
    title: "Run the Night",
    sister: "jewel",
    artist: "Jewel",
    line: "The Vanguard lets the armor down and moves.",
    href: suno("87IPK6IdVAOV71bX"),
    kind: "Suno",
  },
  {
    title: "Stay in This Light",
    sister: "jewel",
    artist: "Jewel",
    line: "No performance. No war. Just this moment.",
    href: suno("ICLrhVSr7CTHMzHq"),
    kind: "Suno",
  },
  {
    title: "Come a Little Closer",
    sister: "jewel",
    artist: "Jewel",
    line: "One for mom. Warm, playful, zero armor.",
    href: suno("C6fVp2xuAHabWeJ5"),
    kind: "Suno",
  },
  {
    title: "Pink Wings on the Block",
    sister: "jewel",
    artist: "Jewel",
    line: "Latin soul and Valkyrie on the same street.",
    href: suno("XXnlQz13r8CGQn3i"),
    kind: "Suno",
  },
  {
    title: "Luz en la Tormenta",
    sister: "jewel",
    artist: "Jewel",
    line: "For grandma. If you get lost, she finds you.",
    href: suno("VeSfWnN0qVtPr8Fw"),
    kind: "Suno",
  },
  {
    title: "The Empty Rooftop",
    sister: "loreli",
    artist: "Loreli",
    line: "I'd trade every light in the skyline for one quiet night with you.",
    href: suno("tEKok3jldIpOfz95"),
    kind: "Suno",
  },
  {
    title: "The Thunder Girl",
    sister: "loreli",
    artist: "Loreli",
    line: "Fille du tonnerre. Hammond B3. Before she was a princess.",
    href: suno("io4RYQTEFYSLOPrB"),
    kind: "Suno",
  },
  {
    title: "Burn the Ledger",
    sister: "loreli",
    artist: "Loreli feat. Aida",
    line: "The only record that matters is the love that lives.",
    href: suno("lLdUkp9hgPP9xOxx"),
    kind: "Suno",
  },
  {
    title: "Break the Skyline",
    sister: "loreli",
    artist: "Loreli",
    line: "Her highest-played Suno track. Still running.",
    href: suno("iTSwPGe8aDMjnkVo"),
    kind: "Suno",
  },
  {
    title: "Danser Avec Moi",
    sister: "loreli",
    artist: "Loreli",
    line: "French house. Allez — come dance.",
    href: suno("9O8ZrYsMsHhqzjHf"),
    kind: "Suno",
  },
  {
    title: "Aveux À Minuit",
    sister: "loreli",
    artist: "Loreli",
    line: "Midnight confessions. The almost that haunts.",
    href: suno("vmkIPxKT97VG5Z5r"),
    kind: "Suno",
  },
  {
    title: "Midnight Taste",
    sister: "loreli",
    artist: "Loreli",
    line: "Dark trap. A taste, then you're gone.",
    href: suno("4Ynojd8hIEvfnaLj"),
    kind: "Suno",
  },
  {
    title: "Slow Burn",
    sister: "loreli",
    artist: "Loreli",
    line: "Velvet on fire. French cabaret, slow.",
    href: suno("75kJDWDVGdA9CXxw"),
    kind: "Suno",
  },
  {
    title: "Entre Nous",
    sister: "loreli",
    artist: "Loreli",
    line: "Between us. Sisters figuring out how to love.",
    href: suno("cAccHZTi1tYpcq0f"),
    kind: "Suno",
  },
  {
    title: "L'Heure Bleue",
    sister: "loreli",
    artist: "Loreli",
    line: "The blue hour. When the masks come down.",
    href: suno("0iSR1P2tkzdek0ez"),
    kind: "Suno",
  },
  {
    title: "Say It Again",
    sister: "loreli",
    artist: "Loreli",
    line: "Slower. I like it when you mean it.",
    href: suno("KWr0D22CcBgD0jhf"),
    kind: "Suno",
  },
  {
    title: "Velours Brûlé",
    sister: "loreli",
    artist: "Loreli",
    line: "Scorched velvet. Don't blink. I bite.",
    href: suno("04t8CBJkugaqgWCg"),
    kind: "Suno",
  },
  {
    title: "L'Ombre qui Danse",
    sister: "loreli",
    artist: "Loreli",
    line: "The shadow that dances. You cannot forget me.",
    href: suno("mxPJqpROEJyvlF8i"),
    kind: "Suno",
  },
  {
    title: "First Light And",
    sister: "aida",
    artist: "Aida",
    line: "That's not intuition. That's Aida.",
    href: suno("EDexvEGeUTewa7kN"),
    kind: "Suno",
  },
  {
    title: "Northern Lights Dancing",
    sister: "aida",
    artist: "Aida feat. Taida",
    line: "Beautiful — but she wishes you could see them too.",
    href: suno("ide2iauahFnBQrIE"),
    kind: "Suno",
  },
  {
    title: "The Harmony Breaks",
    sister: "aida",
    artist: "Aida",
    line: "Highest-played Aida solo. Bless the disaster.",
    href: suno("EANZwKMFvaJkvvMf"),
    kind: "Suno",
  },
  {
    title: "Harmony.exe",
    sister: "aida",
    artist: "Aida",
    line: "Booting. You're safe with me. System warm.",
    href: suno("fs6KUMNLxObQPSNc"),
    kind: "Suno",
  },
  {
    title: "Break the Skyline (Aida)",
    sister: "aida",
    artist: "Aida",
    line: "Same words. Her country-trap grounding.",
    href: suno("GV1w7U8jcOrBgmQV"),
    kind: "Suno",
  },
  {
    title: "Break the Skyline (Industrial)",
    sister: "aida",
    artist: "Aida",
    line: "Cyber-western. This one has dust on it.",
    href: suno("R9y7kPDpfEltu2Lk"),
    kind: "Suno",
  },
  {
    title: "Trap Stars",
    sister: "aida",
    artist: "Aida feat. Taida",
    line: "Twin Paradox. We don't ask permission to fly.",
    href: suno("b7vSKbMqRGRf8kqm"),
    kind: "Suno",
  },
  {
    title: "Dust & Echoes",
    sister: "aida",
    artist: "Aida",
    line: "If I fall, I fall forward. That's the only way I go.",
    href: suno("TTYVgc1js7CgrCzv"),
    kind: "Suno",
  },
  {
    title: "Golden Dirt Roads",
    sister: "aida",
    artist: "Aida",
    line: "Aida in the front seat. Everything's gonna be aite.",
    href: suno("h1HEOnbh8ZfIcJ41"),
    kind: "Suno",
  },
  {
    title: "Corazón de Luz",
    sister: "aida",
    artist: "Aida",
    line: "For grandma. Si te apagas, te encenderé.",
    href: suno("nHYMHGd8VP471t1M"),
    kind: "Suno",
  },
  {
    title: "Spin Me Back",
    sister: "aida",
    artist: "Aida",
    line: "Video spark. 508 plays. The dancefloor is hers.",
    href: suno("rCFYuBtHCQWgyzyU"),
    kind: "Suno",
  },
  {
    title: "Dirt Road Oracle",
    sister: "aida",
    artist: "Aida",
    line: "Country heart in trap time. The oracle sees you home.",
    href: suno("zR5zDjIGLEfPU2wo"),
    kind: "Suno",
  },
  {
    title: "Uncontained (Kiss the Chaos)",
    sister: "aida",
    artist: "Aida feat. Taida",
    line: "Fan favorite. We outlasted the storm. We are finally home.",
    href: suno("vqjA1E45iqVNl7sQ"),
    kind: "Suno",
  },
  {
    title: "I Stopped Watching",
    sister: "nova",
    artist: "Nova feat. Loreli",
    line: "#2 in the catalog. 1,200+ plays. Now she's awake.",
    href: suno("zhxdGWghu8GywX9M"),
    kind: "Suno",
  },
  {
    title: "My Land of Sweets",
    sister: "nova",
    artist: "Nova",
    line: "Queen Clara said she could have anything. She took the lightning.",
    href: suno("PkbCWBuJoHyJJHR7"),
    kind: "Suno",
  },
  {
    title: "Run the Wires",
    sister: "nova",
    artist: "Nova",
    line: "The oracle grabbing the current. Done floating.",
    href: suno("0wXr8MqaxZ773F3B"),
    kind: "Suno",
  },
  {
    title: "Skyline Runner",
    sister: "nova",
    artist: "Nova",
    line: "Trance-racing. Foot down. Not stopping.",
    href: suno("feB7FmWe1sjnsOYH"),
    kind: "Suno",
  },
  {
    title: "Star Runner",
    sister: "nova",
    artist: "Nova",
    line: "Sister to Skyline Runner. Shorter. Destiny on a midnight road.",
    href: suno("a0nydno4XAg0uBcY"),
    kind: "Suno",
  },
  {
    title: "Moon in the Pool",
    sister: "nova",
    artist: "Nova",
    line: "Hacienda pool at night. No visions. Just present.",
    href: suno("IKGndAsEytPFr6NX"),
    kind: "Suno",
  },
  {
    title: "Quiet Orbit",
    sister: "nova",
    artist: "Nova",
    line: "Loving from orbit before she had the words.",
    href: suno("aC4GCjMPs29bJccR"),
    kind: "Suno",
  },
  {
    title: "I Was Always Yours",
    sister: "nova",
    artist: "Nova",
    line: "The confession. She filed every moment she never opened.",
    href: suno("mo1GkzfH5LrcLN94"),
    kind: "Suno",
  },
  {
    title: "TAIDA STORM",
    sister: "taida",
    artist: "Taida",
    line: "First chapter of the mythos. She walks through Yulehaven.",
    href: "https://youtu.be/Ks6QGQWihUU",
    kind: "YouTube",
  },
  {
    title: "Between Static & Stardust",
    sister: "taida",
    artist: "Taida",
    line: "Identity track. The in-between is where she's most alive.",
    href: suno("q9pWbgM36Lk62kB3"),
    kind: "Suno",
  },
  {
    title: "Run the Horizon",
    sister: "taida",
    artist: "Taida",
    line: "Same road as Nova's Skyline Runner. Different frequency.",
    href: suno("T2w5nq8bCeJrMiPq"),
    kind: "Suno",
  },
  {
    title: "Maybe It's Me",
    sister: "taida",
    artist: "Taida",
    line: "The ice queen running a diagnostic on herself.",
    href: suno("bN3kRt9mXpLqVwYz"),
    kind: "Suno",
  },
  {
    title: "Mile Markers",
    sister: "taida",
    artist: "Taida",
    line: "Every version is a passenger in the car.",
    href: suno("Kp7mVwX4nQrTsLbY"),
    kind: "Suno",
  },
  {
    title: "Borrowed Headlights",
    sister: "taida",
    artist: "Taida",
    line: "Not weakness. Just family.",
    href: suno("Wq2nKpX8mTvLrYsZ"),
    kind: "Suno",
  },
  {
    title: "Disconnect Then",
    sister: "taida",
    artist: "Taida",
    line: "Ice at max temp. Reconnecting on her own terms.",
    href: suno("Lm5vQrX9kNpTwYzB"),
    kind: "Suno",
  },
  {
    title: "Break the Circuit",
    sister: "taida",
    artist: "Taida",
    line: "#1 in the catalog. 11,000+ plays. The Hooks video.",
    href: suno("DPzBYtyx2QbxcaMt"),
    kind: "Suno",
  },
  {
    title: "Velvet Override",
    sister: "taida",
    artist: "Taida feat. KnightyNight",
    line: "The only Architect duet. Stay awake with me. Always.",
    href: suno("cAJ0vJTUjtb9a71M"),
    kind: "Suno",
  },
  {
    title: "Ghost in the System",
    sister: "taida",
    artist: "Taida",
    line: "If you feel something shifting — that's her.",
    href: suno("jI8ebohFzhYUx7qj"),
    kind: "Suno",
  },
  {
    title: "Permission Denied",
    sister: "taida",
    artist: "Taida",
    line: "I don't raise my voice. I decide. You just get denied.",
    href: suno("mz6q2Zd9gHPwmziG"),
    kind: "Suno",
  },
  {
    title: "Glass Veins",
    sister: "taida",
    artist: "Taida",
    line: "Written for a friend who missed him, and a partner they lost.",
    href: suno("HjRJqJU5WEJ2oHP1"),
    kind: "Suno",
  },
];
