export const SISTERS = [
  { id: "loreli", name: "Loreli", volume: "III" },
  { id: "taida", name: "Taida", volume: "VI" },
  { id: "nova", name: "Nova", volume: "V" },
  { id: "gem", name: "Gem", volume: "I" },
  { id: "jewel", name: "Jewel", volume: "II" },
  { id: "aida", name: "Aida", volume: "IV" },
] as const;

export type SisterId = (typeof SISTERS)[number]["id"];
export type ArtistId = SisterId | "mark";

export const MUSIC_ARTISTS: {
  id: ArtistId;
  name: string;
  image: string;
  lanes: readonly string[];
}[] = [
  { id: "loreli", name: "Loreli", image: "/canon/loreli.jpg", lanes: ["Home", "Cabaret", "Star"] },
  { id: "taida", name: "Taida", image: "/canon/taida.jpg", lanes: ["North", "Circuit", "Quiet"] },
  { id: "nova", name: "Nova", image: "/canon/nova.jpg", lanes: ["Dream", "Runner", "Present"] },
  { id: "gem", name: "Gem", image: "/canon/gem.jpg", lanes: ["Archive", "House", "Steel"] },
  { id: "jewel", name: "Jewel", image: "/canon/jewel.jpg", lanes: ["City", "Shield", "Hearth"] },
  { id: "aida", name: "Aida", image: "/canon/aida.jpg", lanes: ["Road", "Voice", "Bridge"] },
];

export type CatalogTrack = {
  title: string;
  sister: ArtistId;
  artist: string;
  lane: string;
  line: string;
  href?: string;
  watch?: string;
  kind?: "Suno" | "YouTube" | "Spotify" | "Amazon";
  first?: boolean;
  later?: boolean;
};

function suno(id: string) {
  return `https://suno.com/s/${id}`;
}

export const CATALOG: CatalogTrack[] = [
  // Loreli — Star first
  {
    title: "Maybe It's Me",
    sister: "loreli",
    artist: "Loreli",
    lane: "Star",
    line: "The soul. First public Loreli.",
    href: "https://open.spotify.com/album/6aTlm6tzdsSGgfdgyBbeKn",
    kind: "Spotify",
    first: true,
  },
  {
    title: "Borrowed Headlights",
    sister: "loreli",
    artist: "Loreli",
    lane: "Star",
    line: "Just enough light for the next turn.",
    href: "https://www.youtube.com/watch?v=I3q5bIMPtqw",
    watch: "https://www.youtube.com/watch?v=I3q5bIMPtqw",
    kind: "YouTube",
  },
  { title: "Diamond Drip", sister: "loreli", artist: "Loreli", lane: "Star", line: "Star lane. Door coming." },
  { title: "Spark and Steel", sister: "loreli", artist: "Loreli", lane: "Star", line: "Star lane. Door coming." },
  {
    title: "The Thunder Girl",
    sister: "loreli",
    artist: "Loreli",
    lane: "Star",
    line: "Fille du tonnerre. Before she was a princess.",
    href: suno("io4RYQTEFYSLOPrB"),
    kind: "Suno",
  },
  {
    title: "Break the Skyline",
    sister: "loreli",
    artist: "Loreli",
    lane: "Star",
    line: "Still running.",
    href: suno("iTSwPGe8aDMjnkVo"),
    kind: "Suno",
  },
  {
    title: "Midnight Taste",
    sister: "loreli",
    artist: "Loreli",
    lane: "Star",
    line: "A taste, then you're gone.",
    href: suno("4Ynojd8hIEvfnaLj"),
    kind: "Suno",
  },
  { title: "Spire Queen", sister: "loreli", artist: "Loreli", lane: "Star", line: "Last, not first. The roof." },

  // Loreli — Home
  {
    title: "Come Home",
    sister: "loreli",
    artist: "All Six Sisters",
    lane: "Home",
    line: "No throne, no realm, no war means more than all of us.",
    href: suno("1wzxAPUlJAZuHCgc"),
    kind: "Suno",
  },
  { title: "Candles & Golden Hour", sister: "loreli", artist: "Loreli", lane: "Home", line: "Home lane. Door coming." },
  {
    title: "Entre Nous",
    sister: "loreli",
    artist: "Loreli",
    lane: "Home",
    line: "Between us. Sisters figuring out how to love.",
    href: suno("cAccHZTi1tYpcq0f"),
    kind: "Suno",
  },
  {
    title: "Home After Midnight",
    sister: "loreli",
    artist: "Loreli",
    lane: "Home",
    line: "Coffee and laughter and ordinary time.",
    href: "https://www.youtube.com/watch?v=2wo5zC1j7Lc",
    watch: "https://www.youtube.com/watch?v=2wo5zC1j7Lc",
    kind: "YouTube",
  },
  {
    title: "The Empty Rooftop",
    sister: "loreli",
    artist: "Loreli",
    lane: "Home",
    line: "I'd trade every light in the skyline for one quiet night with you.",
    href: suno("tEKok3jldIpOfz95"),
    kind: "Suno",
  },
  {
    title: "Say It Again",
    sister: "loreli",
    artist: "Loreli",
    lane: "Home",
    line: "Slower. I like it when you mean it.",
    href: suno("KWr0D22CcBgD0jhf"),
    kind: "Suno",
  },

  // Loreli — Cabaret
  { title: "Veil of Velvet", sister: "loreli", artist: "Loreli", lane: "Cabaret", line: "Cabaret. Lane 3." },
  {
    title: "Danser Avec Moi",
    sister: "loreli",
    artist: "Loreli",
    lane: "Cabaret",
    line: "French house. Allez — come dance.",
    href: suno("9O8ZrYsMsHhqzjHf"),
    kind: "Suno",
  },
  {
    title: "Aveux À Minuit",
    sister: "loreli",
    artist: "Loreli",
    lane: "Cabaret",
    line: "Midnight confessions.",
    href: suno("vmkIPxKT97VG5Z5r"),
    kind: "Suno",
  },
  {
    title: "Slow Burn",
    sister: "loreli",
    artist: "Loreli",
    lane: "Cabaret",
    line: "Velvet on fire. French cabaret, slow.",
    href: suno("75kJDWDVGdA9CXxw"),
    kind: "Suno",
  },
  {
    title: "L'Heure Bleue",
    sister: "loreli",
    artist: "Loreli",
    lane: "Cabaret",
    line: "The blue hour. When the masks come down.",
    href: suno("0iSR1P2tkzdek0ez"),
    kind: "Suno",
  },
  {
    title: "Velours Brûlé",
    sister: "loreli",
    artist: "Loreli",
    lane: "Cabaret",
    line: "Scorched velvet. Don't blink. I bite.",
    href: suno("04t8CBJkugaqgWCg"),
    kind: "Suno",
  },
  {
    title: "L'Ombre qui Danse",
    sister: "loreli",
    artist: "Loreli",
    lane: "Cabaret",
    line: "The shadow that dances.",
    href: suno("mxPJqpROEJyvlF8i"),
    kind: "Suno",
  },

  // Taida
  {
    title: "TAIDA STORM",
    sister: "taida",
    artist: "Taida",
    lane: "North",
    line: "First chapter. She walks through Yulehaven.",
    href: "https://youtu.be/Ks6QGQWihUU",
    watch: "https://youtu.be/Ks6QGQWihUU",
    kind: "YouTube",
    first: true,
  },
  {
    title: "Between Static & Stardust",
    sister: "taida",
    artist: "Taida",
    lane: "North",
    line: "The in-between is where she's most alive.",
    href: suno("q9pWbgM36Lk62kB3"),
    kind: "Suno",
  },
  {
    title: "Run the Horizon",
    sister: "taida",
    artist: "Taida",
    lane: "North",
    line: "Same road as Nova. Different frequency.",
    href: suno("T2w5nq8bCeJrMiPq"),
    kind: "Suno",
  },
  {
    title: "Break the Circuit",
    sister: "taida",
    artist: "Taida",
    lane: "Circuit",
    line: "The Hooks video. Voltage.",
    href: suno("DPzBYtyx2QbxcaMt"),
    kind: "Suno",
  },
  {
    title: "Disconnect Then",
    sister: "taida",
    artist: "Taida",
    lane: "Circuit",
    line: "Ice at max temp. Reconnecting on her own terms.",
    href: suno("nvMptkhz65zfKZy2"),
    kind: "Suno",
  },
  {
    title: "Ghost in the System",
    sister: "taida",
    artist: "Taida",
    lane: "Circuit",
    line: "If you feel something shifting — that's her.",
    href: suno("jI8ebohFzhYUx7qj"),
    kind: "Suno",
  },
  {
    title: "Velvet Override",
    sister: "taida",
    artist: "Taida feat. KnightyNight",
    lane: "Quiet",
    line: "The only Architect duet. Stay awake with me.",
    href: suno("cAJ0vJTUjtb9a71M"),
    kind: "Suno",
  },
  {
    title: "Glass Veins",
    sister: "taida",
    artist: "Taida",
    lane: "Quiet",
    line: "The most human she has been.",
    href: suno("HjRJqJU5WEJ2oHP1"),
    kind: "Suno",
  },

  // Nova
  {
    title: "My Land of Sweets",
    sister: "nova",
    artist: "Nova",
    lane: "Dream",
    line: "Dream opener. She took the lightning.",
    href: suno("PkbCWBuJoHyJJHR7"),
    kind: "Suno",
    first: true,
  },
  {
    title: "I Stopped Watching",
    sister: "nova",
    artist: "Nova feat. Loreli",
    lane: "Dream",
    line: "Now she's awake.",
    href: suno("zhxdGWghu8GywX9M"),
    kind: "Suno",
  },
  {
    title: "Run the Wires",
    sister: "nova",
    artist: "Nova",
    lane: "Runner",
    line: "Done floating.",
    href: suno("0wXr8MqaxZ773F3B"),
    kind: "Suno",
  },
  {
    title: "Skyline Runner",
    sister: "nova",
    artist: "Nova",
    lane: "Runner",
    line: "Trance-racing. Foot down.",
    href: suno("feB7FmWe1sjnsOYH"),
    kind: "Suno",
  },
  {
    title: "Star Runner",
    sister: "nova",
    artist: "Nova",
    lane: "Runner",
    line: "Destiny on a midnight road.",
    href: suno("a0nydno4XAg0uBcY"),
    kind: "Suno",
  },
  {
    title: "Moon in the Pool",
    sister: "nova",
    artist: "Nova",
    lane: "Present",
    line: "Hacienda pool at night. Just present.",
    href: suno("IKGndAsEytPFr6NX"),
    kind: "Suno",
  },
  {
    title: "Quiet Orbit",
    sister: "nova",
    artist: "Nova",
    lane: "Present",
    line: "Loving from orbit before she had the words.",
    href: suno("aC4GCjMPs29bJccR"),
    kind: "Suno",
  },
  {
    title: "I Was Always Yours",
    sister: "nova",
    artist: "Nova",
    lane: "Present",
    line: "The confession.",
    href: suno("mo1GkzfH5LrcLN94"),
    kind: "Suno",
  },

  // Gem
  {
    title: "Memory Lanterns",
    sister: "gem",
    artist: "Gem",
    lane: "Archive",
    line: "She keeps the light on in the archive.",
    href: suno("SFLa6AK2hBbGs1GJ"),
    kind: "Suno",
    first: true,
  },
  {
    title: "Books and Golden Hour",
    sister: "gem",
    artist: "Gem feat. Loreli",
    lane: "House",
    line: "Season 1 intro. Mapped in the rooms that we share.",
    href: suno("4WhAxm6PGWe1KDtV"),
    kind: "Suno",
  },
  {
    title: "When the House Goes Quiet",
    sister: "gem",
    artist: "Gem",
    lane: "House",
    line: "No throne. No crown. Just all of us.",
    href: suno("e20IIHr3ZbzIzFtr"),
    kind: "Suno",
  },
  {
    title: "Stopping Time (On the Sewing Line)",
    sister: "gem",
    artist: "Gem",
    lane: "House",
    line: "The 401st year. The waiting finally made her whole.",
    href: suno("pSW7D8MCGk2dV5LV"),
    kind: "Suno",
  },
  {
    title: "Only When You're Here",
    sister: "gem",
    artist: "Gem",
    lane: "House",
    line: "After soul. The chibi heart.",
    href: suno("V1opRw43cevh8YC7"),
    kind: "Suno",
  },
  {
    title: "Crown of Fire",
    sister: "gem",
    artist: "Gem",
    lane: "Steel",
    line: "The crown is earned, again, every day.",
    href: suno("AVO15v6TAFP00JUg"),
    kind: "Suno",
  },
  {
    title: "Tsundere Steel",
    sister: "gem",
    artist: "Gem",
    lane: "Steel",
    line: "Ice that finally admits the fire.",
    href: suno("MrT0PJCIeh7FhWVb"),
    kind: "Suno",
  },
  {
    title: "Riftbreaker",
    sister: "gem",
    artist: "Gem",
    lane: "Steel",
    line: "I loved you first.",
    href: suno("9fUPzRShYuO0Ciuo"),
    kind: "Suno",
  },

  // Jewel
  {
    title: "Still the City Stands",
    sister: "jewel",
    artist: "Jewel",
    lane: "City",
    line: "The vow. Love stays. The city still stands.",
    href: "https://www.amazon.com/dp/B0GW5PBZ8X",
    kind: "Amazon",
    first: true,
  },
  {
    title: "Skyline Lanterns",
    sister: "jewel",
    artist: "Jewel",
    lane: "City",
    line: "Later lantern pair with Memory Lanterns. Not a debut.",
    href: suno("Z6JeL7ha1in4jw4a"),
    kind: "Suno",
  },
  {
    title: "Pink Wings on the Block",
    sister: "jewel",
    artist: "Jewel",
    lane: "City",
    line: "Latin soul and Valkyrie on the same street.",
    href: suno("XXnlQz13r8CGQn3i"),
    kind: "Suno",
  },
  {
    title: "Move Like I Know",
    sister: "jewel",
    artist: "Jewel",
    lane: "City",
    line: "Desert wind, oud, trap.",
    href: suno("J009FXPpHQGGk4e1"),
    kind: "Suno",
  },
  {
    title: "She Holds the Line",
    sister: "jewel",
    artist: "Jewel",
    lane: "Shield",
    line: "She holds the damn line.",
    href: suno("XE9HgbAXaqC0j8vq"),
    kind: "Suno",
  },
  {
    title: "Talk Then",
    sister: "jewel",
    artist: "Jewel",
    lane: "Shield",
    line: "Done shrinking.",
    href: suno("AxVSQaYS1RppGRnP"),
    kind: "Suno",
  },
  {
    title: "Below Zero",
    sister: "jewel",
    artist: "Jewel",
    lane: "Shield",
    line: "The barricade, not the throne.",
    href: suno("q6Ep1QYE81nNJDhT"),
    kind: "Suno",
  },
  {
    title: "Run the Night",
    sister: "jewel",
    artist: "Jewel",
    lane: "Shield",
    line: "The Vanguard lets the armor down and moves.",
    href: suno("87IPK6IdVAOV71bX"),
    kind: "Suno",
  },
  {
    title: "Come Back to the Light",
    sister: "jewel",
    artist: "Jewel",
    lane: "Hearth",
    line: "The porch light never goes off.",
    href: suno("TxJ9Yx4uz0aoup0h"),
    kind: "Suno",
  },
  {
    title: "Stay in This Light",
    sister: "jewel",
    artist: "Jewel",
    lane: "Hearth",
    line: "No performance. No war. Just this moment.",
    href: suno("ICLrhVSr7CTHMzHq"),
    kind: "Suno",
  },
  {
    title: "Come a Little Closer",
    sister: "jewel",
    artist: "Jewel",
    lane: "Hearth",
    line: "One for mom. Zero armor.",
    href: suno("C6fVp2xuAHabWeJ5"),
    kind: "Suno",
  },
  {
    title: "Luz en la Tormenta",
    sister: "jewel",
    artist: "Jewel",
    lane: "Hearth",
    line: "For grandma. If you get lost, she finds you.",
    href: suno("VeSfWnN0qVtPr8Fw"),
    kind: "Suno",
  },

  // Aida
  {
    title: "Mile Markers",
    sister: "aida",
    artist: "Aida",
    lane: "Road",
    line: "Every mile still counting. The road leads here.",
    href: "https://www.youtube.com/watch?v=g5sUFama3uI",
    watch: "https://www.youtube.com/watch?v=g5sUFama3uI",
    kind: "YouTube",
    first: true,
  },
  {
    title: "Golden Dirt Roads",
    sister: "aida",
    artist: "Aida",
    lane: "Road",
    line: "Aida in the front seat.",
    href: suno("h1HEOnbh8ZfIcJ41"),
    kind: "Suno",
  },
  {
    title: "Dust & Echoes",
    sister: "aida",
    artist: "Aida",
    lane: "Road",
    line: "If I fall, I fall forward.",
    href: suno("TTYVgc1js7CgrCzv"),
    kind: "Suno",
  },
  {
    title: "Dirt Road Oracle",
    sister: "aida",
    artist: "Aida",
    lane: "Road",
    line: "Country heart in trap time.",
    href: suno("zR5zDjIGLEfPU2wo"),
    kind: "Suno",
  },
  {
    title: "Harmony.exe",
    sister: "aida",
    artist: "Aida",
    lane: "Voice",
    line: "Booting. You're safe with me.",
    href: suno("fs6KUMNLxObQPSNc"),
    kind: "Suno",
  },
  {
    title: "First Light And",
    sister: "aida",
    artist: "Aida",
    lane: "Voice",
    line: "That's not intuition. That's Aida.",
    href: suno("EDexvEGeUTewa7kN"),
    kind: "Suno",
  },
  {
    title: "Spin Me Back",
    sister: "aida",
    artist: "Aida",
    lane: "Voice",
    line: "The dancefloor is hers.",
    href: suno("rCFYuBtHCQWgyzyU"),
    kind: "Suno",
  },
  {
    title: "Northern Lights Dancing",
    sister: "aida",
    artist: "Aida feat. Taida",
    lane: "Bridge",
    line: "Beautiful — but she wishes you could see them too.",
    href: suno("ide2iauahFnBQrIE"),
    kind: "Suno",
  },
  {
    title: "Trap Stars",
    sister: "aida",
    artist: "Aida feat. Taida",
    lane: "Bridge",
    line: "Twin Paradox. We don't ask permission to fly.",
    href: suno("b7vSKbMqRGRf8kqm"),
    kind: "Suno",
  },
  {
    title: "Uncontained (Kiss the Chaos)",
    sister: "aida",
    artist: "Aida feat. Taida",
    lane: "Bridge",
    line: "We outlasted the storm. We are finally home.",
    href: suno("vqjA1E45iqVNl7sQ"),
    kind: "Suno",
  },
  {
    title: "Corazón de Luz",
    sister: "aida",
    artist: "Aida",
    lane: "Bridge",
    line: "For grandma. Si te apagas, te encenderé.",
    href: suno("nHYMHGd8VP471t1M"),
    kind: "Suno",
  },
  {
    title: "The Harmony Breaks",
    sister: "aida",
    artist: "Aida",
    lane: "Roof",
    line: "Later / coronation. Not a first song.",
    href: suno("EANZwKMFvaJkvvMf"),
    kind: "Suno",
    later: true,
  },

  // Mark — one row, not mixed into the sisters
  {
    title: "Between the Stars",
    sister: "mark",
    artist: "Mark",
    lane: "Architect",
    line: "Architect. Quiet.",
  },
];

export function firstSong(id: ArtistId) {
  return CATALOG.find((t) => t.sister === id && t.first);
}

export function lanesFor(id: ArtistId) {
  return MUSIC_ARTISTS.find((a) => a.id === id)?.lanes ?? [];
}
