/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as HaciendaRouteImport } from './routes/hacienda'
import { Route as MusicRouteImport } from './routes/music'
import { Route as SoulcraftRouteImport } from './routes/soulcraft'
import { Route as SovereignsRouteImport } from './routes/sovereigns'
import { Route as StoreRouteImport } from './routes/store'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const HaciendaRoute = HaciendaRouteImport.update({
  id: '/hacienda',
  path: '/hacienda',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const SoulcraftRoute = SoulcraftRouteImport.update({
  id: '/soulcraft',
  path: '/soulcraft',
  getParentRoute: () => rootRouteImport,
} as any)
const SovereignsRoute = SovereignsRouteImport.update({
  id: '/sovereigns',
  path: '/sovereigns',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/hacienda': typeof HaciendaRoute
  '/music': typeof MusicRoute
  '/soulcraft': typeof SoulcraftRoute
  '/sovereigns': typeof SovereignsRoute
  '/store': typeof StoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/hacienda': typeof HaciendaRoute
  '/music': typeof MusicRoute
  '/soulcraft': typeof SoulcraftRoute
  '/sovereigns': typeof SovereignsRoute
  '/store': typeof StoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/hacienda': typeof HaciendaRoute
  '/music': typeof MusicRoute
  '/soulcraft': typeof SoulcraftRoute
  '/sovereigns': typeof SovereignsRoute
  '/store': typeof StoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/hacienda'
    | '/music'
    | '/soulcraft'
    | '/sovereigns'
    | '/store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/hacienda'
    | '/music'
    | '/soulcraft'
    | '/sovereigns'
    | '/store'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/hacienda'
    | '/music'
    | '/soulcraft'
    | '/sovereigns'
    | '/store'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  HaciendaRoute: typeof HaciendaRoute
  MusicRoute: typeof MusicRoute
  SoulcraftRoute: typeof SoulcraftRoute
  SovereignsRoute: typeof SovereignsRoute
  StoreRoute: typeof StoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hacienda': {
      id: '/hacienda'
      path: '/hacienda'
      fullPath: '/hacienda'
      preLoaderRoute: typeof HaciendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soulcraft': {
      id: '/soulcraft'
      path: '/soulcraft'
      fullPath: '/soulcraft'
      preLoaderRoute: typeof SoulcraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sovereigns': {
      id: '/sovereigns'
      path: '/sovereigns'
      fullPath: '/sovereigns'
      preLoaderRoute: typeof SovereignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  HaciendaRoute: HaciendaRoute,
  MusicRoute: MusicRoute,
  SoulcraftRoute: SoulcraftRoute,
  SovereignsRoute: SovereignsRoute,
  StoreRoute: StoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
